apiVersion: v1
kind: Service
metadata:
  name: alertmanager-main
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: web
    nodePort: 30004
  - name: reloader-web
    port: 8080
    protocol: TCP
    targetPort: reloader-web
  type: NodePort
