apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
    nodePort: 30001
  - name: reloader-web
    port: 8080
    protocol: TCP
    targetPort: reloader-web
    nodePort: 30002
  type: NodePort
